### ISSUE TITLE
Signing in Windows 10

### ISSUE THREAD

**Issue by 0x4a47** [MartinDrab/IRPMon#10]
Hey @MartinDrab, 

Just wondering what the best option is for getting the driver either signed, or loaded on a Windows 10 install. 

I've attempted to turn off the signing checks and enforcement with no luck. I've also attempted to create my own cert for the driver however, am finding that i can't create a .cat file from a .inf because there isn't one! 

Any guidance would be appreciated!

**Comment by MartinDrab** [comment]
Hello,

I plan to sign the driver myself during this weekend. Then it should load fine on the following platforms:
* Windows XP-8.1,
* Windows 10 with no Anniversary Update,
* WIndows 10 post-Anniversary with Secure Boot disabled,
* WIndows 10 that were installed as an update to an older version of Windows, such as Windows 7,
* all 32-bit versions of Windows.

Since I do not have access to an EV code signing certificate, I cannot do the attestation signing myself.

The IRPMon.exe application installs and loads the driver manually which is why there is no INF file needed. The driver also does not require any extra settings, onlz a service representing in inside the Service Control Manager. Howerver, I know that the INF/CAT files are needed for the attestation signing (since MS still seems not to like non-HW drivers), so I will create some just before I sign the driver. Since no extra installation stuff is required (it is just a WDM driver), I will probably use the INF file from the Empty WDM Driver template.

To load the current (unsinged) driver, you should:
1) create your own test certificate with MakeCert,
2) Sign the driver via signtool,
3) enable Test Signing (bcdedit /set testsigning on, and reboot),
4) possibly disable Secure Boot,

Alternatively, the driver seems to load fine when a debugger, such as WinDbg, is connected to the machine (that is, howerver, appliable mostly for virtual machines only).

If you do not have an EV code signing certificate, you actually do not need the INF file and I will solve everything for you during this weekend. If you do have one, I will create INF+CAt for you (and for the whole project) and all should be good. I do not have any experience with the attestation signing process, howerver, so I hope I will do well enough :-).

**Comment by 0x4a47** [comment]
Thanks for your elaborate response, it definitely clears the process up for me. However after trying a couple more signing methods with no success - I will just wait it out and see how i go with your signed version. 👍

**Comment by MartinDrab** [comment]
I forgot tu mention that you must put your test signing certificate to the Trusted Root Certificate Authorities store (and possibly make a reboot).

I am guessing you are still getting the 577 error.

But yes, we will see during the weekend.

**Comment by MartinDrab** [comment]
Well, give me extra 2-3 days to finish the testing. I have the signed package ready but would like to test it on several versions of Windows.

**Comment by MartinDrab** [comment]
I have just released IRPMon v0.8 with signed binaries (the DLL, the GUI application and the driver), so you do not need a test signing in most cases. As I said above, the driver did not go through the attestation signing process.
