### ISSUE TITLE
Static analyzer result - potential issues when building x64

### ISSUE THREAD

**Issue by hfiref0x** [MartinDrab/IRPMon#9]
Hello,

Thanks for sharing your project.

While building your code from commit 0d82265 static analyser I use picked up several potential issues. So I decided to report them.

Release/x64

irpmonconsole/main.cpp
> A different number of actual arguments is expected while calling 'printf' function. Expected: 2. Present: 3. main.cpp 770

`printf("ERROR: Unable to unhook the 0x%p driver\n", *it, err);`

kmshared/utils.c _GetDriversInDirectory
> The 'TmpDriverArray' pointer was utilized before it was verified against nullptr. Check lines: 243, 245. utils.c 243

` RtlCopyMemory(Tmp, TmpDriverArray, TmpDriverCount * sizeof(PDRIVER_OBJECT));`

where TmpDriverArray declared as 
`PDRIVER_OBJECT *TmpDriverArray = NULL;`
and never assigned before use in IF branch.

kmshared/utils.c _GetLowerUpperDevices
same issue as above

kmshared/utils.c _GetDeviceAddress
Status variable assigned twice successively. Perhaps it is a mistake.

libregman/key-reg.c KeyRecordOnQuery

> The 'keyInfo' pointer was utilized before it was verified against nullptr. Check lines: 621, 628. key-record.c 621

This one is tricky, I'm not sure if this can occur because it need more conditions.

keyInfo can be NULL if status >= 0 and Info->Length == 0 plus following ZwQueryKey fail with appreciate status code. Perhaps you could move keyInfo null validation code out of IF statement at line 578.

libtranslate/libtranslate-hash.table.c
HashTableLockShared & HashTableLockExclusive identical routines with different names
HashTableUnlockShared & HashTableUnlockExclusive identical routines with different names

**Comment by MartinDrab** [comment]
Thank you very much for the report. I really should give the static code analysis a try again.

> irpmonconsole/main.cpp

Fixed, thanks.

> utils.c

These should not be problems. In case of the `TmpXxxArray` variables, thez are first used }as null pointers] in a call to `memcpy`, howerver, zero bytes is always copied for the first time. These variables are properly initialized after that. As for the double assignment to the `Status` variable, I do not see this as a mistake, it reflects my programming style --- I begin every function (well, nearly every) with variable declarations and initial assignments, then an entering debug print, hten the routine body actually starts. It may happen that some variable is overriden by another value but this is OK. The reason for initializing the variables with some values before actually needing them helps me to catch errors caused by using a variable without first initializing it (since it usually causes a crash, or a return of STATUS_UNSUCCESSFUL error code). Of course, static analysis may help in this case.

> keyInfo

AFAIR, `keyInfo` is null iff `Info->Length` is yero in which case, ;ZwQueryValueKey; fails (unless a nasty registry filter is present there) and the problematic `memcpy` is never reached. ut I will consider a fix here.

> libtranslate

I consider this as OK, I may implement true reader-writer locks in the future.

**Comment by hfiref0x** [comment]
> I really should give the static code analysis a try again.

I would recommend you try pvs studio, ms analyser is a good too, but pvs can find problems where ms didn't recognized them at all.
